### ISSUE TITLE
Node std issue in deno 1.31.1

### ISSUE THREAD

**Issue by jmordica** [sail-sail/mysql2#7]
https://deno.land/manual@v1.31.1/node/node_specifiers

This is now the recommended way to import node specifiers. Using deno 1.31.1 with this module results in:

```
error: Module not found "https://deno.land/std/node/buffer.ts" at https://deno.land/x/mysql2@v1.0.6/deps.ts:2:24
```

They are no longer publishing a `node` directory in the Deno standard library

**Comment by suchislife801** [comment]
Same here while trying to run a simple SELECT query. Is there any way Node can be completely removed from this project? It is only bound to happen again and again and again until the code is completely devoid of Node in every way.

```bash
error: Uncaught TypeError: core.runMicrotasks is not a function
    core.runMicrotasks();
         ^
    at processTicksAndRejections (https://deno.land/std@0.166.0/node/_next_tick.ts:62:10)
    at https://deno.land/std@0.166.0/node/process.ts:375:7
    at innerInvokeEventListeners (internal:deno_web/02_event.js:783:7)
    at invokeEventListeners (internal:deno_web/02_event.js:823:5)
    at dispatch (internal:deno_web/02_event.js:692:9)
    at dispatchEvent (internal:deno_web/02_event.js:1073:12)
    at [internal:cli\worker.rs:90:39]:1:1
```

**Comment by waptik** [comment]
I'm also facing it with current latest version 
![Screenshot 2023-03-31 at 21 42 11](https://user-images.githubusercontent.com/1687551/229238597-3e81aa9f-e093-4f95-8bdd-b1f0deb5aef3.png)
